stages:
  - setup
  - build
  - test

# Étape 1 : Installation des dépendances
setup:
  stage: setup
  image: python:3.9
  script:
    - pip install -r requirements.txt
  artifacts:
    paths:
      - venv/
  cache:
    paths:
      - venv/

# Étape 2 : Exécution du programme
build:
  stage: build
  image: python:3.9
  script:
    - python hello.py
  artifacts:
    paths:
      - output.txt

# Étape 3 : Exécution des tests unitaires
test:
  stage: test
  image: python:3.9
  script:
    - pip install pytest
    - pytest
  only:
    - main
